www/src/Entity/Project.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;


/**
 * @ORM\Entity(repositoryClass="App\Repository\ProjectRepository")
 * @ORM\Cache(usage="NONSTRICT_READ_WRITE")
 */
class Project
{
	/**
	 * @ORM\Id
	 * @ORM\GeneratedValue
	 * @ORM\Column(type="integer")
	 */
	private $id;

	/**
	 * @ORM\Column(type="string", length=10)
	 */
	private $reference;

	/**
	 * @ORM\Column(type="string", length=200)
	 */
	private $name;

	/**
	 * @ORM\Column(type="string", length=200)
	 */
	private $client;

	/**
	 * @ORM\Column(type="decimal", precision=7, scale=2, nullable=true)
	 */
	private $nbDays;

	/**
	 * @ORM\Column(type="string", length=1000, nullable=true)
	 */
	private $comments;

	/**
	 * @ORM\Column(type="boolean")
	 */
	private $billable=true;

	/**
	 * @ORM\Column(type="boolean")
	 */
	private $archived=true;

	/**
	 * @ORM\OneToMany(targetEntity="App\Entity\Planning", mappedBy="project", orphanRemoval=true)
	 */
	private $plannings;

	/**
	 * @ORM\OneToMany(targetEntity="App\Entity\Task", mappedBy="project", orphanRemoval=true)
	 */
	private $tasks;

	/**
	 * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="managedProjects")
	 * @ORM\JoinColumn(nullable=true,onDelete="SET NULL")
	 */
	private $projectManager;

	/**
	 * @ORM\ManyToOne(targetEntity="Team", inversedBy="projects")
	 */
	private $team;

	/**
	 * @ORM\ManyToOne(targetEntity="App\Entity\ProjectStatus", inversedBy="projects")
	 */
	private $projectStatus;


	public function __construct()
	{
		$this->plannings = new ArrayCollection();
		$this->tasks = new ArrayCollection();
	}

	public function getId(){
		return $this->id;
	}

	public function getReference(){
		return $this->reference;
	}

	public function setReference($reference){
		$this->reference = $reference;
	}

	public function getName(){
		return $this->name;
	}

	public function setName($name){
		$this->name = $name;
	}

	public function getClient(){
		return $this->client;
	}

	public function setClient($client){
		$this->client = $client;
	}

	public function getNbDays(){
		return $this->nbDays;
	}

	public function setNbDays($nbDays){
		if($nbDays < 0) $nbDays=0;
		$this->nbDays = $nbDays;
	}

	public function getComments(){
		return $this->comments;
	}

	public function setComments($comments){
		$this->comments = $comments;
	}

	public function isBillable(){
		return $this->billable;
	}

	public function setBillable($billable){
		$this->billable = $billable?true:false;
	}

	public function isArchived(){
		return $this->archived;
	}

	public function setArchived($archived){
		$this->archived = $archived?true:false;
	}

	/**
	 * @return Collection|Planning[]
	 */
	public function getPlannings()
	{
		return $this->plannings;
	}

	/**
	 * @return Collection|Task[]
	 */
	public function getTasks(){
		return $this->tasks;
	}

	public function getPlannedDays(){
		$slicesPlanned = 0;
		foreach($this->plannings as $planning){
			$slicesPlanned += $planning->getNbSlices();
		}	
		return $slicesPlanned/2;
	}

	public function getProjectManager(){
		return $this->projectManager;
	}

	public function setProjectManager($projectManager){
		$this->projectManager = $projectManager;
	}

	public function getTeam(){
		return $this->team;
	}

	public function setTeam($team){
		$this->team = $team;
	}

	public function __toString(){
		return $this->client.' - '.$this->name;
	}

	public function getProjectStatus()
	{
		return $this->projectStatus;
	}

	public function setProjectStatus($projectStatus)
	{
		$this->projectStatus = $projectStatus;
		return $this;
	}
}

www/src/Entity/Team.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TeamRepository")
 * @ORM\Cache(usage="NONSTRICT_READ_WRITE")
 */
class Team
{
	/**
	 * @ORM\Id()
	 * @ORM\GeneratedValue()
	 * @ORM\Column(type="integer")
	 */
	private $id;

	/**
	 * @ORM\Column(type="string", length=255)
	 */
	private $name;

	/**
	 * @ORM\OneToMany(targetEntity="App\Entity\User", mappedBy="team")
	 */
	private $users;

	/**
	 * @ORM\ManyToMany(targetEntity="User", inversedBy="managedTeams")
	 * @ORM\JoinTable(name="managers_teams")
	 */
	private $managers;

	/**
	 * @ORM\OneToMany(targetEntity="Team", mappedBy="parent", orphanRemoval=false)
	 */
	private $children;

	/**
	 * @ORM\ManyToOne(targetEntity="Team", inversedBy="children")
	 * @ORM\JoinColumn(nullable=true,onDelete="SET NULL")
	 */
	private $parent;

	/**
	 * @ORM\OneToMany(targetEntity="App\Entity\Project", mappedBy="team")
	 */
	private $projects;

	/**
	 * @ORM\OneToMany(targetEntity="App\Entity\ProjectStatus", mappedBy="team", orphanRemoval=true)
	 */
	private $projectStatuses;

	public function __construct() {
		$this->users = new ArrayCollection();
		$this->children = new ArrayCollection();
		$this->projects = new ArrayCollection();
		$this->projectStatuses = new ArrayCollection();
	}

	public function getId()
	{
		return $this->id;
	}

	public function getName()
	{
		return $this->name;
	}

	public function setName(string $name)
	{
		$this->name = $name;

		return $this;
	}

	public function getUsers(){
		return $this->users;
	}

	public function addUser(User $user){
		$this->users[] = $user;
		return $this;
	}

	public function removeUser(User $user){
		if (!$this->users->contains($user)) {
			return $this;
		}
		$this->users->removeElement($user);
		return $this;
	}

	public function getManagers(){
		return $this->managers;
	}

	public function addManager(User $manager){
		$this->managers[] = $manager;
		return $this;
	}

	public function removeManager(User $manager){
		if (!$this->managers->contains($manager)) {
			return $this;
		}
		$this->managers->removeElement($manager);
		return $this;
	}

	public function getChildren(){
		return $this->children;
	}

	public function getRecurChildren(){
		$children = [];
		foreach($this->children as $child){
			$children[] = $child;
			$children = array_merge($children,$child->getRecurChildren());
		}
		return array_unique($children);
	}

	public function addChild($child){
		$this->children[] = $child;
		return $this;
	}

	public function getParent(){
		return $this->parent;
	}

	public function setParent(Team $parent){
		$this->parent = $parent;
		return $this;
	}

	public function getLevel(){
		if($this->parent == NULL){
			return 0;
		}
		return $this->parent->getLevel() + 1;
	}

	public function getProjects(){
		return $this->projects;
	}

	public function __toString(){
		return $this->name;
	}

	public function canAdmin(User $user){
		if(in_array($user,$this->managers->toArray()))
			return true;
		if($this->parent == NULL) return false;
		return $this->parent->canAdmin($user);
	}

	/**
	 * @return Collection|ProjectStatus[]
	 */
	public function getProjectStatuses(): Collection
	{
		return $this->projectStatuses;
	}

	public function addProjectStatus(ProjectStatus $projectStatus)
	{
		if (!$this->projectStatuses->contains($projectStatus)) {
			$this->projectStatuses[] = $projectStatus;
			$projectStatus->setTeam($this);
		}
		return $this;
	}

	public function removeProjectStatus(ProjectStatus $projectStatus)
	{
		if ($this->projectStatuses->contains($projectStatus)) {
			$this->projectStatuses->removeElement($projectStatus);
			if ($projectStatus->getTeam() === $this) {
				$projectStatus->setTeam(null);
			}
		}
		return $this;
	}
}

www/src/Controller/TeamController.php
<?php

namespace App\Controller;

use App\Entity\Team;
use App\Entity\User;
use App\Entity\Project;
use App\Entity\ProjectStatus;
use App\Form\TeamType;
use App\Form\ProjectStatusType;
use App\Form\ProjectType;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

/**
 * @Route("/team")
 */
class TeamController extends Controller
{
    /**
	 * @Route("/", name="team_index")
     */
	public function index(Request $request)
	{
		if(!$this->get('session')->get('user')->isAdmin()){
			throw $this->createNotFoundException("Cette page n'existe pas");
		}

		$em = $this->getDoctrine()->getManager();
		$teamRepository = $this->getDoctrine()->getRepository(Team::class);
		$team = new Team();

		$form = $this->createForm(TeamType::class,$team);
		$form->handleRequest($request);
		if ($form->isSubmitted() && $form->isValid()) {
			$em->persist($team);
			$em->flush();
			$this->addFlash('success','Équipe enregistrée');
			return $this->redirectToRoute('team_index');
		}

		$teams = $teamRepository->findAll();
		return $this->render('team/index.html.twig', [
			"form"=>$form->createView(),
			"teams"=>$teams
        ]);
	}

	/**
	 * @Route("/view/{teamId}",name="team_view",defaults={"teamId"="0"})
	 */
	public function view(Request $request,$teamId){
		$em = $this->getDoctrine()->getManager();
		$teamRepository = $this->getDoctrine()->getRepository(Team::class);
		$projectRepository = $this->getDoctrine()->getRepository(Project::class);
		$userRepository = $this->getDoctrine()->getRepository(User::class);
		$me = $userRepository->find($this->get('session')->get('user')->getId());

		if($teamId == 0){
			$teamId = $me->getTeam()->getId();
		}else{
			$allowedTeams = [];
			$myTeam = $me->getTeam();
			if($myTeam != null) $allowedTeams[] = $myTeam->getId();
			foreach($me->getManagedTeams() as $team){
				$allowedTeams[] = $team->getId();
			}
			if(!$this->get('session')->get('user')->isAdmin() and !in_array($teamId,$allowedTeams)){
				throw $this->createNotFoundException("Cette page n'existe pas");
			}
		}

		if(!($team = $teamRepository->find($teamId))){
			throw $this->createNotFoundException("Cette page n'existe pas");
		}

		$project = new Project();
		$projectForm = $this->createForm(ProjectType::class,$project,['teams'=>[$team],'users'=>$team->getUsers()]);

		$projectForm->handleRequest($request);
		if ($projectForm->isSubmitted() && $projectForm->isValid()) {
			$project = $projectForm->getData();
			if(!$me->canAdmin($project)){
				throw $this->createNotFoundException("Cette page n'existe pas");
			}
			$em->persist($project);
			$em->flush();
			$this->addFlash('success','Projet ajouté');
		}


		$projects = $projectRepository->findAll();

		$managedProjects = [];
		$managedUsers = [];
		if($me->isAdmin()){
			$managedProjects = $projects;
			$managedUsers = $userRepository->findBy(array("isResource"=>true));
		}else{
			foreach($projects as $project){
				if($me->canAdmin($project)){
					$managedProjects[] = $project;
				}
			}
			foreach($team->getUsers() as $user){
				if($me->canAdmin($user)){
					$managedUsers[] = $user;
				}
			}
		}

		try {
			$startDateObj = new \DateTime($startDate);
		} catch (\Exception $e) {
			$startDate = "now";
			$startDateObj = new \DateTime("now");
		}
		$renderMonths = 3;

		$maxOffsets = [];
		for($i=0;$i<$renderMonths;$i++){
			$offDate = clone $startDateObj;
			$offDate->modify("+".$i."months");
			foreach($team->getUsers() as $user){
				$maxOffsets[$i][$user->getId()] = CommonController::calcOffset($offDate,$user);
			}
		}

		return $this->render('team/view.html.twig', [
			'nbMonths' => 3,
			'maxOffsets' => $maxOffsets,
			"team"=>$team,
			"teams" => $teamRepository->findAll(),
			'holidays' => CommonController::getHolidays($startDateObj->format('Y')),
			'startDate' => $startDate,
			'users' => $team->getUsers(),
			'projects' => $projects,
			'projectForm' => $projectForm->createView(),
			'me' => $me,
        ]);
	}

	/**
	 * @Route("/del/{teamId}",name="team_del")
	 */
	public function del(Request $request,$teamId){
		if(!$this->get('session')->get('user')->isAdmin()){
			throw $this->createNotFoundException("Cette page n'existe pas");
		}
		$em = $this->getDoctrine()->getManager();
		$teamRepository = $this->getDoctrine()->getRepository(Team::class);

		if(!($team = $teamRepository->find($teamId))){
			$this->addFlash('danger','Erreur : équipe non trouvée');
		}else{
			$em->remove($team);
			$em->flush();
		}
		$referer = $request->headers->get('referer');
		return $this->redirect($referer);
	}

	/**
	 * @Route("/edit/{teamId}",name="team_edit")
	 */
	public function edit(Request $request,$teamId){
		$em = $this->getDoctrine()->getManager();
		$teamRepository = $this->getDoctrine()->getRepository(Team::class);
		$userRepository = $this->getDoctrine()->getRepository(User::class);
		$projectStatusRepository = $this->getDoctrine()->getRepository(projectStatus::class);
		$me = $userRepository->find($this->get('session')->get('user')->getId());

		if(!($team = $teamRepository->find($teamId))){
			throw $this->createNotFoundException("Cette page n'existe pas");
		}

	if(!$this->get('session')->get('user')->isAdmin()){
			if(!$me->canAdmin($team))
				throw $this->createNotFoundException("Cette page n'existe pas");
		}

		$projectStatus = new ProjectStatus();
		$form = $this->createForm(ProjectStatusType::class,$projectStatus);
		$form->handleRequest($request);
		if ($form->isSubmitted() && $form->isValid()) {
			$projectStatus->setTeam($team);
			$projectStatus->setStatusOrder($projectStatusRepository->findMaxOrder($team)+1);
			$em->persist($projectStatus);
			$em->flush();
			$this->addFlash('success','Statut enregistré');

			$projectStatus = new ProjectStatus();
			$form = $this->createForm(ProjectStatusType::class,$projectStatus);
		}

		return $this->render('team/edit.html.twig', [
			"team"=>$team,
			"users"=>$userRepository->findAll(),
			"form"=>$form->createView(),
			"statuses" => $projectStatusRepository->findByTeam($team)
        ]);
	}

	/**
	 * @Route("/addManager/{teamId}/{userId}",name="team_addManager")
	 */
	public function addManager(Request $request,$teamId,$userId){
		if(!$this->get('session')->get('user')->isAdmin()){
			throw $this->createNotFoundException("Cette page n'existe pas");
		}
		$em = $this->getDoctrine()->getManager();
		$teamRepository = $this->getDoctrine()->getRepository(Team::class);
		$userRepository = $this->getDoctrine()->getRepository(User::class);

		if(!($team = $teamRepository->find($teamId))){
			$arrData = ['success' => false, 'errormsg' => 'Équipe non trouvée'];
		}elseif(!($user = $userRepository->find($userId))){
			$arrData = ['success' => false, 'errormsg' => 'Utilisateur non trouvé'];
		}else{
			$team->addManager($user);
			$em->flush();
			$arrData = ['success' => true];
		}
		return new JsonResponse($arrData);
	}

	/**
	 * @Route("/delManager/{teamId}/{userId}",name="team_delManager")
	 */
	public function delManager(Request $request,$teamId,$userId){
		if(!$this->get('session')->get('user')->isAdmin()){
			throw $this->createNotFoundException("Cette page n'existe pas");
		}
		$em = $this->getDoctrine()->getManager();
		$teamRepository = $this->getDoctrine()->getRepository(Team::class);
		$userRepository = $this->getDoctrine()->getRepository(User::class);

		if(!($team = $teamRepository->find($teamId))){
			throw $this->createNotFoundException("Cette page n'existe pas");
		}elseif(!($user = $userRepository->find($userId))){
			throw $this->createNotFoundException("Cette page n'existe pas");
		}else{
			$team->removeManager($user);
			$em->flush();
		}
		$referer = $request->headers->get('referer');
		return $this->redirect($referer);
	}

	/**
	 * @Route("/orderStatus/{statusId}/{way}",name="team_changeStatusOrder")
	 */
	public function changeStatusOrder(Request $request,$statusId,$way){
		$em = $this->getDoctrine()->getManager();
		$statusRepository = $this->getDoctrine()->getRepository(ProjectStatus::class);
		$userRepository = $this->getDoctrine()->getRepository(User::class);
		$me = $userRepository->find($this->get('session')->get('user')->getId());

		if(!($status = $statusRepository->find($statusId))){
			throw $this->createNotFoundException("Cette page n'existe pas");
		}elseif(!$me->canAdmin($status->getTeam())){
			throw $this->createNotFoundException("Cette page n'existe pas");
		}
		if($way == "dec"){
			$switchWith = $statusRepository->findInTeamByOrder($status->getTeam(),$status->getStatusOrder()+1);
			if($switchWith != NULL){
				$newOrder = $switchWith->getStatusOrder();
				$switchWith->setStatusOrder($status->getStatusOrder());
				$status->setStatusOrder($newOrder);
			}
		}else{
			if($status->getStatusOrder() > 1){
				$switchWith = $statusRepository->findInTeamByOrder($status->getTeam(),$status->getStatusOrder()-1);
				if($switchWith != NULL){
					$newOrder = $switchWith->getStatusOrder();
					$switchWith->setStatusOrder($status->getStatusOrder());
					$status->setStatusOrder($newOrder);
			}

			}
		}
		$em->flush();

		$referer = $request->headers->get('referer');
		return $this->redirect($referer);
	}

	/**
	 * @Route("/delStatus/{statusId}",name="team_delStatus")
	 */
	public function delStatus(Request $request, $statusId){
		$em = $this->getDoctrine()->getManager();
		$statusRepository = $this->getDoctrine()->getRepository(ProjectStatus::class);
		$userRepository = $this->getDoctrine()->getRepository(User::class);
		$me = $userRepository->find($this->get('session')->get('user')->getId());

		if(!($status = $statusRepository->find($statusId))){
			throw $this->createNotFoundException("Cette page n'existe pas");
		}elseif(!$me->canAdmin($status->getTeam())){
			throw $this->createNotFoundException("Cette page n'existe pas");
		}
		$i=1;
		foreach($status->getProjects() as $project){
			$project->setProjectStatus(null);
		}

www/templates/team/edit.html.twig
{% extends 'base.html.twig' %}

{% block pageTitle %}Equipe {{ team.name }}{% endblock %}

{% block body %}
{% set days = ['Dim','Lun','Mar','Mer','Jeu','Ven','Sam'] %}
{% set months = ['','Jan','Fév','Mars','Avr','Mai','Juin','Juil','Août','Sep','Oct','Nov','Déc'] %}

<h1>Equipe {{ team.name }} 
	<a class="btn btn-outline-dark float-right" href="{{ path('team_view',{'teamId':team.id})}}">Retour</a>
</h1>

<h2>Informations</h2>
<div class="row">
	<div class="col">
		<table class="table">
			<tr><th>Membres de l'équipe</th></tr>
			<tbody id="members">
			{% for user in team.users %}
			<tr>
				<td>
					{{ user.fullname }}
				</td>
			</tr>
			{% endfor %}
			</tbody>
		</table>
	</div>
	<div class="col">
		<table class="table">
			<tr><th>Managers de l'équipe</th><th class="actions"></th></tr>
			<tbody id="managers">
			{% for user in team.managers %}
			<tr>
				<td>
					{{ user.fullname }}
				</td><td class="actions">
					{% if app.session.get('user').admin %}
						<a class="text-danger" href='{{ path('team_delManager',{"teamId":team.id,"userId":user.id}) }}'><i title="Supprimer" class="fas fa-trash"></i></a>
						{% endif %}
				</td>
			</tr>
			{% endfor %}
			</tbody>
			<tr>
				<td colspan="2">
					<select id="addManagerId">
						<option value="0"></option>
						{% for user in users if user not in team.managers %}
						<option value="{{ user.id }}">{{ user.fullname }}</option>
						{% endfor %}
					</select>
					<button class="btn btn-sm btn-primary" id="addManager"><span class="fa fa-plus-circle"></span></button>
				</td>
			</tr>
		</table>
	</div>
	<div class="col">
		<table class="table">
			<tr><th colspan="2">Etapes des projets</th><th class="actions"></th></tr>
			<tbody id="statuses">
			{% for status in statuses %}
			<tr>
				<td>{{status.statusOrder }}</td>
				<td>
					{{ status.name }}
				</td><td class="actions">
					<a class="text-secondary" href='{{ path('team_changeStatusOrder',{"statusId":status.id,"way":"inc"}) }}'><i title="Monter" class="fas fa-sort-up"></i></a>
					<a class="text-secondary" href='{{ path('team_changeStatusOrder',{"statusId":status.id,"way":"dec"}) }}'><i title="Descendre" class="fas fa-caret-down"></i></a>
					<a class="text-danger" href='{{ path('team_delStatus',{"statusId":status.id}) }}'><i title="Supprimer" class="fas fa-trash"></i></a>
				</td>
			</tr>
			{% endfor %}
			<tr>
				<td colspan="2">
					{{ form_start(form) }}
					{{ form_widget(form) }}
					{{ form_end(form) }}
				</td>
			</tr>
			</tbody>
		</table>
	</div>

</div>
{% endblock %}

{% block extraJs %}
<script>
$('#addManager').click(function(e){
	newId = $('#addManagerId').val()
	if(newId != 0){
		url= "{{ path("team_addManager",{"teamId":team.id,"userId":"idPlaceHold"}) }}";
		url = url.replace("idPlaceHold",newId);
		$.ajax(url,{
			async:false,
			error:function(xhr,status,error){
				message='<div class="alert alert-danger alert-dismissible fade show" role="alert">\nErreur : ' + error + '\n<button type="button" class="close" data-dismiss="alert" aria-label="Close">\n<span aria-hidden="true">&times;</span>\n</button>\n</div>';
				$('#flashMessages').append(message);
			},
			success:function(data, status, xhr){
				if(data.success){
					url = "{{ path('team_delManager',{'teamId':team.id,'userId':'idPlaceHold'}) }}"
					url = url.replace("idPlaceHold",newId);
					$('#managers').append('<tr><td> ' + $('#addManagerId option:selected').text() + '</td><td class="actions"><a class="text-danger" href="' + url + '"><i title="Supprimer" class="fas fa-trash"></i></a></td></tr>');
					$("#addManagerId option[value='" + newId + "']").remove();
				}else{
					message='<div class="alert alert-danger alert-dismissible fade show" role="alert">\nErreur : ' + data.errormsg + '\n<button type="button" class="close" data-dismiss="alert" aria-label="Close">\n<span aria-hidden="true">&times;</span>\n</button>\n</div>';
					$('#flashMessages').append(message);
				}
			}
		});

	}
});
</script>
{% endblock %}

www/templates/team/index.html.twig
{% extends "base.html.twig" %}

{% block pageTitle %}Equipes{% endblock %}

{% block body %}
<h1>Gestion des équipes</h1>
<h2>Ajouter une équipe</h2>

{{ form_start(form) }}
{{ form_widget(form) }}
{{ form_end(form) }}

<h2>Équipes existantes</h2>
<table class="table table-sm table-hover">
	<tr><th>Nom</th><th>Membres</th><th>Responsables</th><th></th></tr>
	{% for team in teams if team.level==0%}
		{{printTeam(team)}}
	{% endfor %}
</table>

{% endblock %}