www/src/Entity/Project.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;


/**
 * @ORM\Entity(repositoryClass="App\Repository\ProjectRepository")
 * @ORM\Cache(usage="NONSTRICT_READ_WRITE")
 */
class Project
{
	/**
	 * @ORM\Id
	 * @ORM\GeneratedValue
	 * @ORM\Column(type="integer")
	 */
	private $id;

	/**
	 * @ORM\Column(type="string", length=10)
	 */
	private $reference;

	/**
	 * @ORM\Column(type="string", length=200)
	 */
	private $name;

	/**
	 * @ORM\Column(type="string", length=200)
	 */
	private $client;

	/**
	 * @ORM\Column(type="decimal", precision=7, scale=2, nullable=true)
	 */
	private $nbDays;

	/**
	 * @ORM\Column(type="string", length=1000, nullable=true)
	 */
	private $comments;

	/**
	 * @ORM\Column(type="boolean")
	 */
	private $billable=true;

	/**
	 * @ORM\Column(type="boolean")
	 */
	private $archived=true;

	/**
	 * @ORM\OneToMany(targetEntity="App\Entity\Planning", mappedBy="project", orphanRemoval=true)
	 */
	private $plannings;

	/**
	 * @ORM\OneToMany(targetEntity="App\Entity\Task", mappedBy="project", orphanRemoval=true)
	 */
	private $tasks;

	/**
	 * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="managedProjects")
	 * @ORM\JoinColumn(nullable=true,onDelete="SET NULL")
	 */
	private $projectManager;

	/**
	 * @ORM\ManyToOne(targetEntity="Team", inversedBy="projects")
	 */
	private $team;

	/**
	 * @ORM\ManyToOne(targetEntity="App\Entity\ProjectStatus", inversedBy="projects")
	 */
	private $projectStatus;


	public function __construct()
	{
		$this->plannings = new ArrayCollection();
		$this->tasks = new ArrayCollection();
	}

	public function getId(){
		return $this->id;
	}

	public function getReference(){
		return $this->reference;
	}

	public function setReference($reference){
		$this->reference = $reference;
	}

	public function getName(){
		return $this->name;
	}

	public function setName($name){
		$this->name = $name;
	}

	public function getClient(){
		return $this->client;
	}

	public function setClient($client){
		$this->client = $client;
	}

	public function getNbDays(){
		return $this->nbDays;
	}

	public function setNbDays($nbDays){
		if($nbDays < 0) $nbDays=0;
		$this->nbDays = $nbDays;
	}

	public function getComments(){
		return $this->comments;
	}

	public function setComments($comments){
		$this->comments = $comments;
	}

	public function isBillable(){
		return $this->billable;
	}

	public function setBillable($billable){
		$this->billable = $billable?true:false;
	}

	public function isArchived(){
		return $this->archived;
	}

	public function setArchived($archived){
		$this->archived = $archived?true:false;
	}

	/**
	 * @return Collection|Planning[]
	 */
	public function getPlannings()
	{
		return $this->plannings;
	}

	/**
	 * @return Collection|Task[]
	 */
	public function getTasks(){
		return $this->tasks;
	}

	public function getPlannedDays(){
		$slicesPlanned = 0;
		foreach($this->plannings as $planning){
			$slicesPlanned += $planning->getNbSlices();
		}	
		return $slicesPlanned/2;
	}

	public function getProjectManager(){
		return $this->projectManager;
	}

	public function setProjectManager($projectManager){
		$this->projectManager = $projectManager;
	}

	public function getTeam(){
		return $this->team;
	}

	public function setTeam($team){
		$this->team = $team;
	}

	public function __toString(){
		return $this->client.' - '.$this->name;
	}

	public function getProjectStatus()
	{
		return $this->projectStatus;
	}

	public function setProjectStatus($projectStatus)
	{
		$this->projectStatus = $projectStatus;
		return $this;
	}
}

www/src/Controller/CommonController.php
<?php

namespace App\Controller;

class CommonController{

	public static function getHolidays($baseYear, $format = "U"){
		$holidays = array();
		for($i=-1;$i<=1;$i++){
			$year=$baseYear+$i;
			$easterDate  = \easter_date($year);
			$easterDay   = date('j', $easterDate);
			$easterMonth = date('n', $easterDate);
			$easterYear  = date('Y', $easterDate);

			// Dates fixes
			$holidays[] = mktime(0, 0, 0, 1,  1,  $year);  // 1er janvier
			$holidays[] = mktime(0, 0, 0, 5,  1,  $year);  // Fête du travail
			$holidays[] = mktime(0, 0, 0, 5,  8,  $year);  // Victoire des alliés
			$holidays[] = mktime(0, 0, 0, 7,  14, $year);  // Fête nationale
			$holidays[] = mktime(0, 0, 0, 8,  15, $year);  // Assomption
			$holidays[] = mktime(0, 0, 0, 11, 1,  $year);  // Toussaint
			$holidays[] = mktime(0, 0, 0, 11, 11, $year);  // Armistice
			$holidays[] = mktime(0, 0, 0, 12, 25, $year);  // Noel

			// Dates variables
			$holidays[] = mktime(0, 0, 0, $easterMonth, $easterDay + 1,  $easterYear);
			$holidays[] = mktime(0, 0, 0, $easterMonth, $easterDay + 39, $easterYear);
			$holidays[] = mktime(0, 0, 0, $easterMonth, $easterDay + 50, $easterYear);
		}

		sort($holidays);

		array_walk(
			$holidays,
			function(&$value) use ($format) {
				$value = date(
					$format,
					$value
				);
			}
		);

		return $holidays;
	}

	public static function calcOffset($startDate,$user){
		$maxOffset = 0;
		for($sliceIter=1;$sliceIter<=$startDate->format("t")*2;$sliceIter++){
			$curDate = new \Datetime($startDate->format("m")."/".ceil($sliceIter/2)."/".$startDate->format("Y"));
			$hour = $sliceIter%2==1?"am":"pm";
			foreach($user->getPlannings() as $planning){
				if($planning->getStartDate() == $curDate && $planning->getStartHour() == $hour){
					$offCount=0;
					while(isset($offset[$sliceIter][$offCount])) $offCount++;
					//on est sur le slice de départ du projet
					$filledSlices = $planning->getNbSlices();
					$durationDate = clone $curDate;
					for($durationIter=0 ; $durationIter < $filledSlices ; $durationIter++){
						if($durationDate->format('N') >= 6) $filledSlices++;
						$offset[$sliceIter+$durationIter][$offCount] = $planning;
						$durationDate->modify('+12hours');
					}
					$planning->offset = $offCount; 
					if($offCount > $maxOffset) $maxOffset = $offCount; 
				}
			}
		}
		return $maxOffset;
	}
}

www/src/Controller/common.php
<?php

namespace App\Controller;

class common{

	public static function getHolidays($baseYear){
		$holidays = array();
		for($i=-1;$i<=1;$i++){
			$year=$baseYear+$i;
			$easterDate  = \easter_date($year);
			$easterDay   = date('j', $easterDate);
			$easterMonth = date('n', $easterDate);
			$easterYear  = date('Y', $easterDate);

			// Dates fixes
			$holidays[] = mktime(0, 0, 0, 1,  1,  $year);  // 1er janvier
			$holidays[] = mktime(0, 0, 0, 5,  1,  $year);  // Fête du travail
			$holidays[] = mktime(0, 0, 0, 5,  8,  $year);  // Victoire des alliés
			$holidays[] = mktime(0, 0, 0, 7,  14, $year);  // Fête nationale
			$holidays[] = mktime(0, 0, 0, 8,  15, $year);  // Assomption
			$holidays[] = mktime(0, 0, 0, 11, 1,  $year);  // Toussaint
			$holidays[] = mktime(0, 0, 0, 11, 11, $year);  // Armistice
			$holidays[] = mktime(0, 0, 0, 12, 25, $year);  // Noel

			// Dates variables
			$holidays[] = mktime(0, 0, 0, $easterMonth, $easterDay + 1,  $easterYear);
			$holidays[] = mktime(0, 0, 0, $easterMonth, $easterDay + 39, $easterYear);
			$holidays[] = mktime(0, 0, 0, $easterMonth, $easterDay + 50, $easterYear);
		}
		sort($holidays);
		return $holidays;
	}
}

www/templates/common/addPlanningModals.html.twig
<div class="modal fade" id="overrun_Modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
		  <h5 class="modal-title" id="exampleModalLabel">Dépassement</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Ajouter ce planning va entraîner un dépassement sur le projet. Continuer quand même ?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Annuler</button>
        <button type="button" class="btn btn-primary" onclick="sendPlanningNewRequest();">Continuer</button>
      </div>
    </div>
  </div>
</div>


<div class="modal fade" id="addPlanning_Modal" tabindex="-1" role="dialog">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="addModal_title">Ajout d'une entrée au planning</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<button type="button" class="btn btn-sm float-right" data-toggle="collapse" data-target="#addProject" aria-expanded="false" aria-controls="addProject">+ projet</button>

				<div class="collapse" id="addProject">
					<h4>Ajouter un projet</h4>
					<dl class="row">

					<dt class="col-sm-5">Équipe :</dt>
					<dd class="col-sm-7">
						<select id="project_ajax_team" name="project[team]">
							{% for team in teams %}
								<option value="{{ team.id }}">{{ team.name }}</option>
							{% endfor %}
						</select>
					</dd>

					<dt class="col-sm-5">Code projet :</dt>
					<dd class="col-sm-7">
						<input type="text" id="project_ajax_reference" name="project[reference]" required="required">
					</dd>

					<dt class="col-sm-5">Nom du projet :</dt>
					<dd class="col-sm-7">
						<input type="text" id="project_ajax_name" name="project[name]" required="required">
					</dd>

					<dt class="col-sm-5">Client :</dt>
					<dd class="col-sm-7">
						<input type="text" id="project_ajax_client" name="project[client]" required="required">
					</dd>

					<dt class="col-sm-5">Responsable projet :</dt>
					<dd class="col-sm-7">
						<select id="project_ajax_projectManager" name="project[projectManager]">
							{% for user in users %}
								<option value="{{ user.id }}">{{ user.fullname }}</option>
							{% endfor %}
						</select>
					</dd>

					<dt class="col-sm-5">Facturable :</dt>
						<dd class="col-sm-7">
							<input id="project_ajax_billable" name="project[billable]" type="checkbox" value="1" checked="checked">
						</dd>
					<dt class="col-sm-5">Archivé :</dt>
						<dd class="col-sm-7">
							<input id="project_ajax_archived" name="project[archived]" type="checkbox" value="1">
						</dd>

					<dt class="col-sm-5">Jours vendus :</dt>
					<dd class="col-sm-7">
						<input type="text" id="project_ajax_nbDays" name="project[nbDays]" required="required">
					</dd>

					<dt class="col-sm-5">Commentaires :</dt>
						<dd class="col-sm-7">
							<textarea id="project_ajax_comments" name="project[comments]" class="form-control"></textarea>
						</dd>
					</dl>
	
					<input type="hidden" id="project_ajax_token" name="project[_token]" value="{{ csrf_token('project_add') }}"/>

					<button type="button" class="btn btn-secondary" data-toggle="collapse" data-target="#addProject" aria-expanded="false" aria-controls="addProject">Annuler</button>
					<button type="button" class="btn btn-primary float-right" onclick="projectAdd()">Ajouter</button>

					<div class="clearfix"></div>

					<hr />
				</div>

				<dl class="row">
					<dt class="col-sm-5">Ressource :</dt>
						<dd class="col-sm-7">
							<span id="addModal_ressource"></span>
							<span class="d-none" id="addModal_ressourceForm"></span>
						</dd>
					<dt class="col-sm-5">Date de démarrage :</dt>
						<dd class="col-sm-7">
							<span id="addModal_startDate"></span> (<span id="addModal_startHour"></span>)
							<span class="d-none" id="addModal_startDateForm"></span>
							<span class="d-none" id="addModal_startHourForm"></span>
						</dd>
					<dt class="col-sm-5">Durée :</dt>
						<dd class="col-sm-7">
							<span id="addModal_duration"></span>
							<span class="d-none" id="addModal_durationForm"></span>
						</dd>
					<dt class="col-sm-5">Confirmé :</dt>
						<dd class="col-sm-7">
							<input id="addForm_confirmed" type="checkbox" checked>
						</dd>
					<dt class="col-sm-5">Important :</dt>
						<dd class="col-sm-7">
							<input id="addForm_meeting" type="checkbox">
						</dd>
					<dt class="col-sm-5">Livrable :</dt>
						<dd class="col-sm-7">
							<input id="addForm_deliverable" type="checkbox">
						</dd>
					<dt class="col-sm-5">Réunion :</dt>
						<dd class="col-sm-7">
							<input id="addForm_meetup" type="checkbox">
						</dd>
					<dt class="col-sm-5">Capitalisation :</dt>
						<dd class="col-sm-7">
							<input id="addForm_capitalization" type="checkbox">
						</dd>
					<dt class="col-sm-5">Suivi :</dt>
						<dd class="col-sm-7">
							<input id="addForm_monitoring" type="checkbox" checked>
						</dd>
					<dt class="col-sm-5">Projet :</dt>
						<dd class="col-sm-7">
							<select id="addForm_projectId">
								<option value="0">Absence</option>
								{% for project in projects %}
									{% if not project.archived and me.canAdmin(project) %}
									<option value="{{ project.id }}">{{ project.client }} - {{ project.name }}{% if project.nbDays is not null and project.nbDays != 0%} ({{ project.nbDays - project.plannedDays }}jh rest.){% endif %}</option>
									{% endif %}
								{% endfor %}
							</select>
						</dd>
					<dt class="col-sm-5">Tâche :</dt>
						<dd class="col-sm-7">
							<select id="addForm_taskId" disabled="disabled">
								<option value="0" id="nullTask"></option>
							</select>
						</dd>
					<dt class="col-sm-5">Commentaires :</dt>
						<dd class="col-sm-7">
							<textarea id="addForm_comments" class="form-control"></textarea>
						</dd>

				</dl>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
				<button type="button" class="btn btn-primary" onclick="addPlanning()">Ajouter</button>
			</div>
		</div>
	</div>
</div>